# Generated by Django 5.0.6 on 2024-06-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesslog",
            name="useragent",
            field=models.CharField(default="Unknown", max_length=600),
        ),
    ]
