# Generated by Django 5.0.6 on 2024-06-25 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project1", "0002_accesslog_useragent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accesslog",
            name="useragent",
        ),
    ]
