# Generated by Django 5.0.6 on 2024-06-27 05:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project1", "0004_pdfinfo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pdfinfo",
            old_name="user",
            new_name="created_by",
        ),
    ]
