# Generated by Django 5.0.6 on 2024-06-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project1", "0006_remove_pdfinfo_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdfinfo",
            name="output_folder_path",
            field=models.CharField(max_length=200),
        ),
    ]
