# Generated by Django 5.0.6 on 2024-06-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project1", "0007_alter_pdfinfo_output_folder_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfinfo",
            name="input_file_path",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
